#!/bin/bash

echo "🔒 SmartSpark Services - Deployment Security Checklist"
echo "=================================================="

echo ""
echo "✅ BEFORE PUSHING TO GITHUB:"
echo "1. Sensitive data is in .gitignore"
echo "2. .env.local is NOT committed"
echo "3. Database files are ignored"
echo "4. No hardcoded credentials in code"

echo ""
echo "✅ VPS DEPLOYMENT STEPS:"
echo "1. Set environment variables on VPS:"
echo "   - DATABASE_URL"
echo "   - JWT_SECRET (32+ characters)"
echo "   - NEXTAUTH_SECRET (32+ characters)"
echo "   - GMAIL_USER & GMAIL_APP_PASSWORD"
echo ""
echo "2. Generate strong secrets:"
echo "   openssl rand -base64 32"
echo ""
echo "3. Set up SSL certificate"
echo "4. Configure firewall"
echo "5. Set up database backups"

echo ""
echo "🚨 SECURITY WARNINGS:"
echo "- Never commit .env files"
echo "- Use different secrets for production"
echo "- Enable HTTPS only"
echo "- Regular security updates"

echo ""
echo "📊 OPTIMIZATION STATUS:"
echo "✅ Next.js optimized build"
echo "✅ Image optimization enabled"
echo "✅ Compression enabled"
echo "✅ Security headers configured"
echo "⚠️  Consider CDN for images"

echo ""
echo "🚀 READY FOR DEPLOYMENT: YES (after setting VPS environment variables)"